# Grafana Datasource Configuration for Streaming Feature Store
# Comprehensive datasource setup for monitoring and observability

apiVersion: 1

# Delete existing datasources (clean setup)
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  # Primary Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      # Custom query editor settings
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: 'jaeger-uid'  # if Jaeger is added
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      # Cache settings
      cacheLevel: High
      # Query optimization
      disableMetricsLookup: false
      customQueryParameters: 'max_source_resolution=5m&partial_response=true'
    secureJsonData: {}

  # Prometheus for long-term storage (if configured)
  # - name: Prometheus-LTS
  #   type: prometheus
  #   access: proxy
  #   orgId: 1
  #   url: http://prometheus-lts:9090
  #   editable: true
  #   jsonData:
  #     httpMethod: POST
  #     queryTimeout: 120s
  #     timeInterval: 5m

  # Loki for log aggregation (if deployed)
  # - name: Loki
  #   type: loki
  #   access: proxy
  #   orgId: 1
  #   url: http://loki:3100
  #   editable: true
  #   jsonData:
  #     httpHeaderName1: 'X-Scope-OrgID'
  #     timeout: 60
  #     maxLines: 1000
  #   secureJsonData:
  #     httpHeaderValue1: 'tenant1'

  # Jaeger for distributed tracing (if deployed)
  # - name: Jaeger
  #   type: jaeger
  #   access: proxy
  #   orgId: 1
  #   uid: jaeger-uid
  #   url: http://jaeger:16686
  #   editable: true
  #   jsonData:
  #     tracesToLogs:
  #       datasourceUid: 'loki-uid'
  #       tags: ['job', 'instance', 'pod', 'namespace']
  #       mappedTags: [{ key: 'service.name', value: 'service' }]
  #       mapTagNamesEnabled: false
  #       spanStartTimeShift: '1h'
  #       spanEndTimeShift: '1h'
  #       filterByTraceID: false
  #       filterBySpanID: false

  # InfluxDB for business metrics (if used)
  # - name: InfluxDB
  #   type: influxdb
  #   access: proxy
  #   orgId: 1
  #   url: http://influxdb:8086
  #   database: streaming_fs_business_metrics
  #   user: grafana
  #   editable: true
  #   jsonData:
  #     httpMode: GET
  #     keepCookies: []
  #   secureJsonData:
  #     password: 'password'

  # TestData for dashboard development
  - name: TestData
    type: testdata
    access: proxy
    orgId: 1
    editable: true
    jsonData: {}

# Global datasource settings
# These apply to all datasources
global:
  # HTTP settings
  timeout: 60
  # Query settings
  queryTimeout: 60s
  # UI settings
  defaultDatasource: Prometheus