# Prometheus Configuration for Streaming Feature Store
# Production-grade monitoring configuration with comprehensive service discovery

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'streaming-feature-store'
    environment: 'production'

# Alert rule files (disabled until services are running)
# rule_files:
#   - "alert_rules.yml"
#   - "recording_rules.yml"

# Alertmanager configuration (disabled for now)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Scrape configurations for all services
scrape_configs:
  # === INFRASTRUCTURE MONITORING ===
  
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Feature Store monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis-feature-store'

  # Kafka/Redpanda monitoring  
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9644']  # Redpanda admin API
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node exporter for system metrics (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # === APPLICATION MONITORING ===

  # FastAPI Inference Service - Primary service
  - job_name: 'inference-api'
    static_configs:
      - targets: ['inference-api:8080']
    metrics_path: /metrics
    scrape_interval: 10s  # High frequency for real-time monitoring
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'inference-api'
      - source_labels: [__address__]
        target_label: component
        replacement: 'ml-serving'

  # Stream Processing Service
  - job_name: 'stream-processor'
    static_configs:
      - targets: ['stream-processor:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'stream-processor'
      - source_labels: [__address__]
        target_label: component
        replacement: 'feature-engineering'

  # Event Generators monitoring
  - job_name: 'event-generators'
    static_configs:
      - targets: 
        - 'txn-generator:8001'
        - 'click-generator:8002'
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: generator_type
        replacement: '${1}'

  # === ML PIPELINE MONITORING ===

  # MLflow Tracking Server
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: /metrics
    scrape_interval: 60s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'mlflow-tracking'
      - source_labels: [__address__]
        target_label: component
        replacement: 'ml-lifecycle'

  # Feast Feature Store (when available)
  - job_name: 'feast-server'
    static_configs:
      - targets: ['feast-server:6566']
    metrics_path: /metrics
    scrape_interval: 30s
    honor_labels: true

  # Training Job metrics (when running)
  - job_name: 'training-jobs'
    static_configs:
      - targets: ['training-job:8003']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  # === BUSINESS METRICS ===
  
  # Custom business metrics endpoint
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['inference-api:8080']
    metrics_path: /business-metrics
    scrape_interval: 60s
    honor_labels: true

  # === EXTERNAL MONITORING ===

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://inference-api:8080/health
        - http://inference-api:8080/ready
        - http://mlflow:5000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # === SERVICE DISCOVERY (for Kubernetes) ===
  
  # Kubernetes service discovery (uncomment for K8s deployment)
  # - job_name: 'kubernetes-services'
  #   kubernetes_sd_configs:
  #     - role: service
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
  #       action: keep
  #       regex: true
  #     - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
  #       action: replace
  #       target_label: __metrics_path__
  #       regex: (.+)

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (for query federation)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"