apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 15s
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      disableMetricsLookup: false
    secureJsonData: {}
